### ISSUE TITLE
Cannot run model on amazon dataset

### ISSUE THREAD

**Issue by HansiZeng** [Moonet/AHN#1]
I first run the script file 
```python data_pp_amazon.py``` and set output_dir to ```./data/amazon_auto/amau_5core/automotive/```   
Then after getting the input dataset, I run the model script
```
export GLUE_DIR=./data

PYTHONPATH=../ CUDA_VISIBLE_DEVICES=1,2,3 python ahn_lstm.py \
  --task_name YELP \
  --do_train \
  --do_eval \
  --do_lower_case \
  --data_dir $GLUE_DIR/amazon_auto/amau_5core/automotive/ \
  --num_head 1 \
  --num_reviews 12 \
  --num_sentence 12 \
  --max_seq_length 24 \
  --train_batch_size 128 \
  --learning_rate 2e-4 \
  --num_train_epochs 6.0 \
  --vocab_file vocab.txt \
  --cache_dir  ./data_cache/amau/amau_5core/ \
  --output_dir /tmp/amau_ahn_c5_output/
```
However, the error is
```
Traceback (most recent call last):
  File "ahn_lstm.py", line 771, in <module>
    main()
  File "ahn_lstm.py", line 538, in main
    with open(args.data_dir + 'id_list.pkl', "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/amazon_auto/amau_5core/automotive/id_list.pkl'
```

**Comment by Moonet** [comment]
You can directly run ./ahn_lstm_run.sh without preprocessing data. 
As for id_list.pkl, you need to save the list of ids for users and items based on train.pkl.
